### ISSUE TITLE
how can we query ip addresses ?

### ISSUE THREAD

**Issue by ozkanpakdil** [massimocandela/bulk-whois-parser#4]
Hi

can you please show how to filter by ip "1.2.3.4" ? or can we query by domain name like abc.com ? how about ipv6.

Thanks

**Comment by massimocandela** [comment]
Hi @ozkanpakdil,

Please, refer to the usage example in the readme. In particular, whatever filtering you would like to have has to be implemented in the filterFunction. E.g., for ipv6, a function like the following would suffice `(item) => item.inet6num === '2001:67c:370::/48'`. You cannot query for domain names, this package is for RIR data.
